Sprint3
Gorgeousanya/react-burger pull request #3
Opened 2022-05-02 20:06 UTC by Gorgeousanya

2022-05-03 01:29 UTC, grishbar requested changes
Большая работа проделана, практически весь функицонал работает корректно, круто, что уже пишешь компоненты на ts, есть несколько моментов, которые надо исправить для принятия работы:

- Сейчас менять не надо, но на будущее ветки лучше называть согласно принятой семантике, то есть твоя ветка должны была называться - sprint-3/step-1
- [ ] Обрати внимание, у тебя в консоли есть ворнинги при запуске приложения, их быть не должно, избавься от них пожалуйста
- [x] Не работает сохранение аутентифицированного пользователя, каждый раз при обновлении страницы приходится заново авторизироваться, так быть не должно
- [ ] В шапке должна подсвечиваться только активная ссылка, также стили активной ссылки не соответствуют макету, поправь пожалуйста
- [ ] Поле пароль на странице /login валидируется не совсем корректно, каждый раз при потери фокуса, оно пишет, что заполнено не верно, должно выводить такую плашку, только в случае, если поле пустое
- [ ] Не сделана важная часть задания, смотри 7 пункт - Доработка роутинга в приложении, при клике на ингредиент, у тебя должна открываться новая страница для каждого ингредиента
- [x] Надо поправить типы (избавиться от object)
- [x] Разделить большой редьюсер на более мелкие

2022-05-03 01:29 UTC, grishbar commented on react-burger/package.json
> +    "react-uuid": "^1.0.2",
`надо исправить`
у тебя есть библиотека uuid, так, что кажется, что библиотека react-uuid излишняя оставь только одну из них. В продуктовой разработке добавление новой библиотеки всегда должно быть оправданно, так как добавление новых зависимостей в твой проект, во первых значительно увеличивает его размеры, а во вторых добавляет новых уязвимостей, если вдруг какая то библиотека откажет, или еще что нибудь с ней произойдет

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/app-header/app-header.tsx
> +        }}>
`надо исправить`
 [нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html) давай избавимся от этого, и пройдись пожалуйста по всему проекту, вижу, что есть еще места, где создаешь функции внутри jsx

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/burger-constructor/burger-constructor.tsx
> +        handleClose={() => { dispatch(deleteIngredient(item?.uuid)); }}
`надо исправить` 
Давай здесь и во всех подобных случаях добавим [action creators ](https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#using-action-creators) , и тогда таки штука и будет называть deleteIngredient, так как обычный action должен называться как существительное так как это просто функция которая возвращает объект то есть твой deleteIngredient должен быть назван как getDeleteIngredientAction или deletingIngredient а твой action creator уже будет называться deleteIngredient

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/burger-constructor/burger-constructor.tsx
> +  const constructor = useSelector((state: RootStateOrAny) => state.constructor);
`можно лучше` 
будет лучше если ты тут будешь вовзвращать пустой массив, если state.constructor нет, то есть:
```
const constructor = useSelector((state: RootStateOrAny) => state.constructor ?? []);
```
таким образом тебе не придется ниже проверять на наличие constructor прежде чем мапиться по нему ил что нибудь делать, твой код станет напорядок чище

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/burger-constructor/burger-constructor.tsx
> +        onClose={() => { dispatch({ type: CLOSE_MODAL_ORDER }); dispatch({ type: CLEAR_ORDER }); }}
`надо исправить`
тут тоже не забудь вынести в action creator и убрать создание функции из jsx

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/ingredient-detail/ingredients-details.tsx
> +  console.log(props.ingredient);
`надо исправить`
    комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/order-details/order-details.tsx
> +  console.log(props.order)
`надо исправить` 
тут также не забудь удалить consol log

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/order-details/order-details.tsx
> +  order: PropTypes.object,
`надо исправить` 
старайся не писать такие типы как object или any так как такая типизаця не приносит тебе никакой пользы, что типизирован компонент, что нет, ты можешь положить все что угодно, теряешь основной смысл типов - предотвращение совсем глупых ошибок, так, что распиши здесь пожалуйста, что у тебя за тип тут должен приходить

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/pages/forgot-password.tsx
> +  };
`отлично`

прикольное решение с хранением состояния формы, довольно универсальное получилось

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/pages/forgot-password.tsx
> +  }
`надо исправить` 
посмотри внимательно в задании про работу с аутентификационными токенам, как их хранить и передевать, и на этой основе определяй когда редиректить а когда нет

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/components/pages/register.tsx
> +                        placeholder={'Имя'}
`можно лучше` 
такие пропсы лучше передавать просто строкой, так как фигурные скобочки обозначают подключение js и лучше их не ипсользовать без надобности, так как без них во первых читается проще, во вторых, могу ошибаться, но хоть и незначительно но это замедляет рендер компонента
```
type="text"
placeholder="Имя"
```

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/services/reducers/index.js
> +            }
`надо исправить` 
Делать один большой редьюсер это плохая практика, масштабирование, чтение, исправление такого редьюсера с каждой новой итерацией будет занимать все больше времени, и в какой то момент станет совсем трудозатратным, раздели пожалуйста этот редьюсер на логические более мелкие редьюсеры, например форма ингридиента, оформление заказана, редьюсер аутентификации и так далее, а тут просто объедени все твои редьюсеры при помощи [combineReducers](https://redux.js.org/api/combinereducers)

2022-05-03 01:29 UTC, grishbar commented on react-burger/src/services/reducers/index.js
> +            }
`надо исправить`
    При ошибке в запросе надо возвращать - initialState и error: true , так как не хочется держать в хранилище потенциально невалидные данные, также вижу, что в других местах допущена подобная ошибка не забудь в них тоже поправить пожалуйста

2022-05-10 12:39 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная, но есть некоторые недочеты:


* функция `checkResponse` дублируется в разных файлах. Нужно было ее в `utils.js` 1 раз создать и импортировать туда, где нужно
* под попапом ингредиента виднеется страница с ингредиентом, а такого не должно быть. Под попапом должна виднеться главная страница с конструктором и ингердиентами. Только после вставки ссылки в браузер страница должна отображаться без попапа. Скрин http://joxi.ru/DrlW6XVSKn8lQA
* Если есть инпуты, то они должны быть внутри тега `form`, и на этот тег `form` нужно навешивать обработчик `onSubmit`, а не обработчик `onClick` на кнопку сабмита.
* Обработчик сабмита нужно навешивать только на тег `form` с событием `submit`, а не на кнопку сабмита с событием `click`, так как сабмит формы происходит ещё при нажатии `Enter`, и он не будет работать, если навесить обработчик клика на кнопку только. Это нужно исправить везде, где есть инпуты и форма 
* страница с деталями не должна расплываться на весь экран. Скрин http://joxi.ru/brRxJ96TBVoXq2
* при каждом открытии попапа идет запрос ингредиентов с сервера. Этого не нужно делать. `getIngredientsData()` достаточно 1 раз сделать в `App`, чтобы все страницы получили ингредиенты при загрузке сайта. Не нужно дублировать запрос в других компонентах. В `IngredientDetails` нужно удалить этот запрос
* Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://reactrouter.com/web/example/modal-gallery . Пожалуйста, посоветуйтесь с наставником.
* текст не должен прилипать к краям блока. Скрин http://joxi.ru/12MRE9jtgXoDKA . Нужно отступы сделать небольшие
* Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью `location.state.from` (эти данные записываются в `ProtectedRoute`


**Можно лучше**


*  при клике на логотип обычно идет переход на главную страницу
* Чтобы не дублировать типы экшенов и сами объекты с `type`, принято выносить их в отдельные функции, называемые `action creator` (функцию, которая возвращает объект с `type`). Это позволяет сделать понятное название для функции, которое будет говорить, что делает она, и избавит от повтора объекта с `type` в коде. Подробнее тут: [https://rajdee.gitbooks.io/redux-in-russian/content/docs/basics/Actions.html#генераторы-экшенов-action-creators](https://rajdee.gitbooks.io/redux-in-russian/content/docs/basics/Actions.html#%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D1%8D%D0%BA%D1%88%D0%B5%D0%BD%D0%BE%D0%B2-action-creators)


Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

Удачного рефакторинга кода.

2022-05-10 12:39 UTC, gennady-bars commented on react-burger/src/components/pages/forgot-password.tsx
> +            <Input
Если есть инпуты, то они должны быть внутри тега `form`, и на этот тег `form` нужно навешивать обработчик `onSubmit`, а не обработчик `onClick` на кнопку сабмита.

2022-05-10 12:39 UTC, gennady-bars commented on react-burger/src/components/pages/forgot-password.tsx
> +          <Button type="secondary" size="medium" onClick={onLogin}>
`onClick={onLogin}`

это нужно удалить с кнопки


Обработчик сабмита нужно навешивать только на тег `form` с событием `submit`, а не на кнопку сабмита с событием `click`, так как сабмит формы происходит ещё при нажатии `Enter`, и он не будет работать, если навесить обработчик клика на кнопку только. Это нужно исправить везде, где есть инпуты и форма

2022-05-10 12:39 UTC, gennady-bars commented on react-burger/src/components/pages/login.tsx
> +      <Redirect to={"/"} />
Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью `location.state.from` (эти данные записываются в `ProtectedRoute`

2022-05-14 12:53 UTC, gennady-bars reviewed
Еще немного и все будет отлично:


* нужно в каждой `thunk`-функции проверять ответ вот так `.then(checkResponse)`. А у Вас нет проверки на `ok` в некоторых местах. В `auth.js`, например, только `return res.json();` почти везде
* папку `pages` нужно вынести из `components`, так как она должна лежать рядом с ней, чтобы ее можно было сразу же увидеть
* Вы не исправили кое-что: 
    * Если есть инпуты, то они должны быть внутри тега `form`, и на этот тег `form` нужно навешивать обработчик `onSubmit`, а не обработчик `onClick` на кнопку сабмита.
    * Обработчик сабмита нужно навешивать только на тег `form` с событием `submit`, а не на кнопку сабмита с событием `click`, так как сабмит формы происходит ещё при нажатии `Enter`, и он не будет работать, если навесить обработчик клика на кнопку только. Это нужно исправить везде, где есть инпуты и форма 
 * по заданию нужно сделать логику, при которой бы показывался попап с деталями ингредиента, если кликнуть по ингредиенту, но если скопировать ссылку на ингредиент при открытом попапе и вставить в окно браузера, то должна уже показываться страница с этими деталями ингредиента. 
 * Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью `location.state.from` (эти данные записываются в `ProtectedRoute`. Это в Login нужно прописать 
 * Не могу восстановить пароль. В консоли ошибка при попытке это сделать. СКрин http://joxi.ru/MAj5QOltdLk362 
 *

2022-05-17 08:42 UTC, gennady-bars approved these changes
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-05-19 08:23 UTC, closed without merging